[[animations]]
direction = 'side'
name = 'melee-slash'
    [[animations.frames]]
    stack = [
        {img = 'side/background-0.png', offset-x = 0, offset-y = 0},
        {img = 'side/melee-slash/body-0.png', offset-x = 0, offset-y = 0},
        {img = 'side/head-0.png', offset-x = 0, offset-y = 0},
        {img = 'side/foreground-0.png', offset-x = 0, offset-y = 0}
    ]
    [[animations.frames]]
    stack = [
        {img = 'side/background-0.png', offset-x = 0, offset-y = 0},
        {img = 'side/melee-slash/body-1.png', offset-x = 0, offset-y = 0},
        {img = 'side/head-0.png', offset-x = 0, offset-y = 0},
        {img = 'side/foreground-0.png', offset-x = 0, offset-y = 0}
    ]
    [[animations.frames]]
    stack = [
        {img = 'side/background-0.png', offset-x = 0, offset-y = 0},
        {img = 'side/melee-slash/body-2.png', offset-x = -4, offset-y = 0},
        {img = 'side/head-0.png', offset-x = 5, offset-y = 0},
        {img = 'side/foreground-0.png', offset-x = 0, offset-y = 0}
    ]
    [[animations.frames]]
    stack = [
        {img = 'side/background-0.png', offset-x = 0, offset-y = 0},
        {img = 'side/melee-slash/body-3.png', offset-x = 0, offset-y = 0},
        {img = 'side/head-0.png', offset-x = 3, offset-y = 0},
        {img = 'side/foreground-0.png', offset-x = 0, offset-y = 0}
    ]
    [[animations.frames]]
    stack = [
        {img = 'side/background-0.png', offset-x = 0, offset-y = 0},
        {img = 'side/melee-slash/body-4.png', offset-x = 0, offset-y = 0},
        {img = 'side/head-0.png', offset-x = 3, offset-y = 3},
        {img = 'side/foreground-0.png', offset-x = 0, offset-y = 0}
    ]
